apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-server
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  destination:
    name: in-cluster
    namespace: my-server
  source:
    path: gitops/single-service
    repoURL: https://github.com/vitalii-codefresh/simple-server.git
    targetRevision: develop
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
