apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: product2
spec:
  project: vitalii-git-src-restr-secur
  destination:
    name: in-cluster
    namespace: cf-ns
  source:
    path: gitops/single-service
    repoURL: https://github.com/vitalii-codefresh/simple-server.git
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
