apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: some-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  destination:
    name: in-cluster
    namespace: some-ns
  source:
    path: .
    repoURL: https://github.com/vitalii-codefresh/simple-server.git
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
